config/routes.rb
#
# Copyright (C) 2014 - present Instructure, Inc.
#
# This file is part of Rollcall.
#
# Rollcall is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Rollcall is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

require "resque/server"

InstructureRollcall::Application.routes.draw do
  resources :seating_charts, only: [:show, :create]

  resources :statuses

  get '/courses/:course_id',   to: 'sections#course', as: 'course'
  get '/sections/:section_id', to: 'sections#show', as: 'section'
  scope '/courses/:course_id' do
    resources :students, only: [:show] do
      resources :student_statuses, only: [:index] do
        get 'summary', on: :collection
      end
    end
  end

  get 'course/:course_id/badges', to: 'badges#course'

  resources :accounts, only: [:show] do
    member do
      get :badges
    end
  end

  resources :badges
  resources :awards, only: [:index, :create, :destroy] do
    collection do
      get 'stats'
    end
  end
  resources :course_configs
  resources :reports, only: [:create, :new]

  get 'liveness', to: 'home#liveness'
  get 'readiness', to: 'home#readiness'
  root to: 'home#index'

  mount SecureResqueServer.new, at: "/resque"
  mount LtiProvider::Engine, at: "/"
  mount CanvasOauth::Engine, at: "/canvas_oauth"

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
end

app/models/section.rb
#
# Copyright (C) 2014 - present Instructure, Inc.
#
# This file is part of Rollcall.
#
# Rollcall is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Rollcall is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

class Section
  attr_accessor :id, :name, :students, :course_id, :sis_id

  def initialize(params={})
    params.symbolize_keys!

    self.id = params[:id]
    self.name = params[:name]
    self.course_id = params[:course_id]
    self.sis_id = params[:sis_id]
    self.students = params[:students] ? Student.active_list_from_params(params[:students]) : []
  end

  def to_param
    id
  end

  def self.list_from_params(list=[])
    new_list = list.collect { |params| new(params) }
    new_list.sort_by! { |s| s.name }
  end
end

app/controllers/sections_controller.rb
#
# Copyright (C) 2014 - present Instructure, Inc.
#
# This file is part of Rollcall.
#
# Rollcall is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Rollcall is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

class SectionsController < ApplicationController
  before_action :can_grade

  def course
    prepare_course

    if section_id = enrollments_section_ids(params[:course_id]).first
      redirect_to section_path(section_id)
    elsif section = load_and_authorize_sections(params[:course_id]).first
      redirect_to section_path(section.id)
    else
      render_error
    end
  end

  def show
    @section = load_and_authorize_full_section(params[:section_id])
    return render_error if @section.blank?

    @sections = load_and_authorize_sections(@section.course_id)

    if section_limited?(@section.course_id)
      authorized_section_ids = enrollments_section_ids(@section.course_id)
      @sections.select! { |sec| authorized_section_ids.include?(sec.id) }
      @section = nil unless authorized_section_ids.include?(@section.id)
    end

    render_error if @section.blank? || @sections.blank?

    @course_config = CourseConfig.where(
      course_id: @section.course_id,
      tool_consumer_instance_guid: tool_consumer_instance_guid
    ).first_or_initialize
  end

  private
  def render_error
    render plain: "There was an error loading your section. Please try re-launching the tool."
  end

  def prepare_course
    refresh_course!(params[:course_id])
  end

  def enrollments_section_ids(course_id)
    enrollments = load_and_authorize_enrollments(user_id, course_id) || []
    enrollments.map { |enrollment| enrollment['course_section_id'] }
  end

  def section_limited?(course_id)
    enrollments = load_and_authorize_enrollments(user_id, course_id) || []
    enrollments.present? &&
      enrollments.all?{ |e| e['limit_privileges_to_course_section'] }
  end
end

app/views/sections/_backbone_init.html.erb
<%
# Copyright (C) 2014 - present Instructure, Inc.
#
# This file is part of Rollcall.
#
# Rollcall is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Rollcall is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>
<script type="text/javascript">
  $(function() {
    config = new InstructureRollcall.Models.CourseConfig(<%= @course_config.to_json.html_safe %>);
    
    window.router = new InstructureRollcall.Routers.StatusesRouter(
      { sectionId: <%= @section.id %>,
        courseId: <%= @section.course_id %>,
        courseConfig: config
    });

    Backbone.history.start();    
  });
</script>

app/views/sections/_header.html.erb
<%
# Copyright (C) 2014 - present Instructure, Inc.
#
# This file is part of Rollcall.
#
# Rollcall is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Rollcall is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>
<header id="app-header">
  <div class="block-box one-half first-box">
    <h1 class="light-text-color"><%= link_to "Roll Call", root_path %></h1>
  </div>
  <div class="block-box one-half last-box clearfix">

    <% if controller_name == 'sections' %>
      <div class="block-box three-quarters first-box">
        <ul class="unstyled-list list-class-toggle" role="tablist">
          <li id="show-class" role="tab">
            <a role="button" href="#" class="undecorated-link no-select" title="switch to seating chart" tabindex="0">Class</a>
          </li>
          <li id="show-list" class="active-toggle" role="tab">
            <a role="button" href="#" class="undecorated-link no-select" title="switch to list of students" tabindex="0">List</a>
          </li>
        </ul>
      </div>

      <div class="block-box one-quarter last-box">
        <div class="right rollcall-dropdown settings-dropdown arrow-right-side">
          <a role="button" id="settings-dropdown-toggle" href="#" title="Roll Call settings and reporting" class="replace-text rollcall-dropdown-toggle" aria-haspopup="true">Settings</a>
          <div class="rollcall-dropdown-list visuallyhidden">
            <ul class="unstyled-list" role="menubar">
              <li role="menuitem" tabindex="0"><a href="#" id="settings-toggle">Roll Call Settings</a></li>
              <li role="menuitem" tabindex="-1"><%= link_to "Attendance Report", new_report_path(course_id: course_id) %></li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>

  </div>
</header>

app/views/sections/index.html.erb
<%
# Copyright (C) 2014 - present Instructure, Inc.
#
# This file is part of Rollcall.
#
# Rollcall is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Rollcall is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>
<h1>Sections in this course</h1>

<ul>
  <% @sections.each do |section| %>
    <li><%= link_to section.name, section_path(section) %></li>
  <% end %>
</ul>

app/views/sections/show.html.erb
<%
# Copyright (C) 2014 - present Instructure, Inc.
#
# This file is part of Rollcall.
#
# Rollcall is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Rollcall is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>
<%= render "header", course_id: @section.course_id %>

<div class="sections-select">
  <select id='section_select'>
  <% @sections.each do |section| %>
    <option value='<%= section.id %>' <%= 'selected' if section.id == @section.id %>>
      <%= sanitize section.name %>
    </option>
  <% end %>
  </select>
</div>

<div id="statuses" class="clearfix"></div>

<%= render 'backbone_init' %>