config/routes.rb
#
# Copyright (C) 2014 - present Instructure, Inc.
#
# This file is part of Rollcall.
#
# Rollcall is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Rollcall is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

require "resque/server"

InstructureRollcall::Application.routes.draw do
  resources :seating_charts, only: [:show, :create]

  resources :statuses

  get '/courses/:course_id',   to: 'sections#course', as: 'course'
  get '/sections/:section_id', to: 'sections#show', as: 'section'
  scope '/courses/:course_id' do
    resources :students, only: [:show] do
      resources :student_statuses, only: [:index] do
        get 'summary', on: :collection
      end
    end
  end

  get 'course/:course_id/badges', to: 'badges#course'

  resources :accounts, only: [:show] do
    member do
      get :badges
    end
  end

  resources :badges
  resources :awards, only: [:index, :create, :destroy] do
    collection do
      get 'stats'
    end
  end
  resources :course_configs
  resources :reports, only: [:create, :new]

  get 'liveness', to: 'home#liveness'
  get 'readiness', to: 'home#readiness'
  root to: 'home#index'

  mount SecureResqueServer.new, at: "/resque"
  mount LtiProvider::Engine, at: "/"
  mount CanvasOauth::Engine, at: "/canvas_oauth"

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
end

app/controllers/accounts_controller.rb
#
# Copyright (C) 2014 - present Instructure, Inc.
#
# This file is part of Rollcall.
#
# Rollcall is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Rollcall is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

class AccountsController < ApplicationController
  before_action :can_admin_report

  def show
    redirect_to new_report_path(account_id: params[:id])
  end

  def badges
    @account_id = params[:id]
  end
end

app/views/accounts/_tabs.html.erb
<%
# Copyright (C) 2014 - present Instructure, Inc.
#
# This file is part of Rollcall.
#
# Rollcall is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Rollcall is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>
<section class="last">
  <ul class="unstyled-list sections-list clearfix" role="tablist">
    <li role="tab" <%= params[:action] == "new" ? 'class="active-section" aria-selected="true"'.html_safe : nil %>>
      <%= link_to "Generate report", new_report_path(account_id: @account_id || @canvas_account_json['id'])  %>
    </li>
    <li role="tab" <%= params[:action] == "badges" ? 'class="active-section" aria-selected="true"'.html_safe : nil %>>
      <%= link_to "Manage badges", badges_account_path(id: @account_id || @canvas_account_json['id']) %>
    </li>
  </ul>
</section>

app/views/accounts/badges.html.erb
<%
# Copyright (C) 2014 - present Instructure, Inc.
#
# This file is part of Rollcall.
#
# Rollcall is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Rollcall is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>
<%= render "tabs" %>

<div class="pad-box">
  <div id="content"></div>
</div>

<script type="text/javascript">
  $(function() {
    new InstructureRollcall.Views.Accounts.BadgesView({el: $('#content'), account_id: <%= @account_id %>})
  });
</script>

app/views/accounts/show.html.erb
<%
# Copyright (C) 2014 - present Instructure, Inc.
#
# This file is part of Rollcall.
#
# Rollcall is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Rollcall is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>
<%= render "tabs" %>